# Generated by Django 3.2 on 2021-05-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210517_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pavilhao',
            options={'verbose_name': 'Pavilhão', 'verbose_name_plural': 'Pavilhões'},
        ),
        migrations.AddField(
            model_name='pavilhao',
            name='capacidade',
            field=models.IntegerField(default=116),
        ),
    ]
