# Generated by Django 3.2 on 2021-05-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210517_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pavilhao',
            options={'ordering': ['id'], 'verbose_name': 'Pavilhão', 'verbose_name_plural': 'Pavilhões'},
        ),
        migrations.AddField(
            model_name='pavilhao',
            name='restante',
            field=models.IntegerField(default=0),
        ),
    ]
